"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { Loader2, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { api, setTokens } from "@/lib/api/client";

type Response = { mfa_required?: boolean; mfa_token?: string; tokens?: { access_token: string; refresh_token: string } };
export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [code, setCode] = useState(""); const [mfaToken, setMfaToken] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const finish = (res: Response) => { if (!res.tokens) throw new Error("Incomplete admin session response"); setTokens(res.tokens.access_token, res.tokens.refresh_token); router.replace("/admin"); router.refresh(); };
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(null); try { const res = await api.post<Response>("/v1/admin/auth/login", { email, password }, { auth: false }); if (res.mfa_required) setMfaToken(res.mfa_token ?? null); else finish(res); } catch (e) { setError(e instanceof Error ? e.message : "Unable to sign in"); } finally { setLoading(false); } }
  async function verify(event: React.FormEvent) { event.preventDefault(); if (!mfaToken) return; setLoading(true); setError(null); try { finish(await api.post<Response>("/v1/admin/auth/mfa/verify", { mfa_token: mfaToken, code }, { auth: false })); } catch (e) { setError(e instanceof Error ? e.message : "Invalid MFA code"); } finally { setLoading(false); } }
  return <div className="auth-shell"><div className="auth-card"><div className="auth-lockup"><Image src="/logo-512.png" alt="Ngamia" width={36} height={36} className="rounded-lg" /><span className="text-lg font-semibold tracking-tight">Ngamia Admin</span></div><h1 className="auth-card-heading">{mfaToken ? "Verify your identity" : "Administrator sign in"}</h1><p className="auth-card-subtext">{mfaToken ? "Enter the 6-digit code from your authenticator app." : "Secure access to platform operations."}</p><div className="auth-form">{error && <div className="callout callout-danger mb-4">{error}</div>}{mfaToken ? <form onSubmit={verify} className="flex flex-col gap-4"><div><Label htmlFor="code">Authenticator code</Label><Input id="code" autoFocus inputMode="numeric" maxLength={6} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))} className="mt-1.5 text-center text-xl tracking-[0.5em]" placeholder="000000" /></div><Button type="submit" disabled={loading || code.length !== 6} className="h-10 w-full">{loading && <Loader2 className="h-4 w-4 animate-spin" />}{loading ? "Verifying…" : "Verify and continue"}</Button><button type="button" className="text-sm text-muted-foreground underline" onClick={() => { setMfaToken(null); setCode(""); }}>Use a different account</button></form> : <form onSubmit={submit} className="flex flex-col gap-4"><div><Label htmlFor="email">Admin email</Label><Input id="email" type="email" autoComplete="username" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-1.5" required /></div><div><Label htmlFor="password">Password</Label><Input id="password" type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-1.5" required /></div><Button type="submit" disabled={loading} className="h-10 w-full">{loading && <Loader2 className="h-4 w-4 animate-spin" />}{loading ? "Signing in…" : "Sign in securely"}</Button></form>}</div><p className="mt-6 flex items-center justify-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4" /> Administrator accounts only</p></div></div>;
}
